version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: xfce4-night-mode
    main: ./cmd/xfce4-night-mode/
    binary: xfce4-night-mode
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - files:
      - xfce4-night-mode.service
      - LICENSE
      - README.md

nfpms:
  - id: default
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    vendor: brooqs
    homepage: https://github.com/brooqs/xfce4-night-mode
    maintainer: brooqs
    description: "XFCE4 Night Mode — Automatic theme switching based on sunrise/sunset"
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: ./xfce4-night-mode.service
        dst: /usr/lib/systemd/user/xfce4-night-mode.service

checksum:
  name_template: 'checksums.txt'

aurs:
  - name: xfce4-night-mode
    homepage: https://github.com/brooqs/xfce4-night-mode
    description: "XFCE4 Night Mode — Automatic theme switching based on sunrise/sunset"
    maintainers:
      - "brooqs <brooqs@users.noreply.github.com>"
    license: "MIT"
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/xfce4-night-mode-bin.git'
    package: |-
      install -Dm755 "${srcdir}/xfce4-night-mode" "${pkgdir}/usr/bin/xfce4-night-mode"
      install -Dm644 "${srcdir}/xfce4-night-mode.service" "${pkgdir}/usr/lib/systemd/user/xfce4-night-mode.service"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
